title: Simulationstechniken
description: Dokumentation der Vorlesung Simulationstechniken - Theorie und Praxis.
theme: just-the-docs

url: https://argreiner.github.io/SimulationstechnikenWS26_27

plugins:
  - jekyll-default-layout
